buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'eclipse'

version = "1.0"
group = "com.yourname.modid"
archivesBaseName = "modid"

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'

    runs {
        client {
            workingDirectory project.file('run')

            args '--username', 'gg'

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.debug.export', 'true'

            mods {
                examplemod {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'

            mods {
                examplemod {
                    source sourceSets.main
                }
            }
        }
    }

    accessTransformer = file('src/main/resources/META-INF/narutomod_at.cfg')
}

sourceSets {
    main { output.resourcesDir = output.classesDir }
}


jar {
    manifest {
        attributes(
                'FMLCorePlugin': 'net.narutomod.goatee.mixin.early.NarutoEarlyMixins',
                'FMLCorePluginContainsMod': 'false', // Set to true if the plugin also has @Mod
        )
    }
}


repositories {
    maven {
        url 'https://maven.cleanroommc.com'
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2855'

    annotationProcessor 'org.ow2.asm:asm-debug-all:5.2'
    annotationProcessor 'com.google.guava:guava:32.1.2-jre'
    annotationProcessor 'com.google.code.gson:gson:2.8.9'

    implementation('zone.rong:mixinbooter:10.6') {
        transitive = false
    }
    annotationProcessor('zone.rong:mixinbooter:10.6') {
        transitive = false
    }

  //  implementation((project.files("libs/dojutsuslot-1.0.0.jar")))
    //  implementation((project.files("libs/mixinbooter-9.1.jar")))
}

apply from: 'mcreator.gradle'

tasks.whenTaskAdded { task ->
    if (task.name == "runClient" || task.name == "runServer") {
        task.jvmArgs += "-Dfml.coreMods.load=net.narutomod.goatee.mixin.early.NarutoEarlyMixins"
    }
}

